### ISSUE TITLE
Want to add search bar and improve css

### ISSUE THREAD

**Issue by avishaan24** [IumoInfinium/todo#3]

**Comment by IumoInfinium** [comment]
Hii @avishaan24
Feel free to do so.

**Comment by avishaan24** [comment]
Hii @IumoInfinium 
I updated which is required in this project

**Comment by avishaan24** [comment]
Hii I updated the js file and css to improve the functionality and UI of
the to do list. So merge my pull request as soon as possible. It would be
better for myself
Thanks

**Comment by avishaan24** [comment]
Hii @IumoInfinium could you explain breifly the functional error you face in my pull request. It would be helpful to me to solve the issue.

**Comment by avishaan24** [comment]
As I checked one more time with my offline compiler it works perfectly so if you explain the issue I will definitely try to solve the issue

**Comment by IumoInfinium** [comment]
Some Issues which I found -

- The github icon at the top-right got diminshed.
- There were 2️⃣  input boxes for adding a new task, all we need is 1️⃣  (old and new, i would prefer the old one, it looked better with continuous elements)
- The delete and edit/save feature needs to be slightly more polished, as i couldn't tell the difference, when was which button active and the content was not centred as well.
- And finally the borders were too-much eye-catching!

This might be too much, so you can try to do it one step at a time. Feel free to ask for any help.
Thank you
Iumo

**Comment by avishaan24** [comment]
Hii @IumoInfinium,
Solution to the issues raised by you
* I mistakenly diminished the size of github icon due to provide
responsiveness.
* And at first explain what I have done, In the top after to-do list there
is search bar from where anyone can search any of their tasks then as you
made a windows reloader button I didn't make any changes on that, then
there is input box from where anyone can add their new tasks and after that
add-task button which is used to add the task. I think there is no two
boxes to add new tasks.
* Now, I explain the function of delete, edit/ save button. As whenever
anyone add task from above input then the task added in the list but it's
only in reading mode, noone can edit without pressing the edit button when
anyone press the edit button then the button automatically changes to save
button and the task is in write mode from which anyone edit their task and
save it. After pressing the save button, button changes to edit button and
task changes to readonly mode & delete button is used to delete the tasks.
* As you add changing background so providing any fixed colour border
didn't work on some images and look likes eye catching. So, my suggestion
is to fixed the background image and then add border colour to improve UI.
* And I change all text-alignment to center.
That's all from my side.
Waiting for your suggestion.
Thanks

**Comment by IumoInfinium** [comment]
Hii @avishaan24 
Yeah, now its pretty clear, what was happening.
Thank you
